version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app.jar"]
    depends_on:
      - db
  db:
    env_file:
      - .env.docker
    image: postgres:alpine
    restart: always
    ports:
      - "5438:5432"